version: "3"

services:

  app:
    build:
      context: node
      dockerfile: dockerfile
    container_name: node
    entrypoint: dockerize -wait tcp://db-desafio:3306 -timeout 20s npm start
    volumes:
      - ./node/:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - desafio
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-desafio
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    image: caioadauri/nginx:latest
    container_name: nginx-desafio
    networks:
      - desafio
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  desafio:
    driver: bridge
